### ISSUE TITLE
/giveLegacies has a misleading title

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#106]
If you retype in this command, it wipes any legacies you had before. So, I did it once, and I got glacien, I put in the command, expecting more, and I got Lumen, but I did not have glacien anymore.

**Comment by lukawarren** [comment]
Yeah, it's by design. If you want to get more legacies, that's where the Loric Stone comes in. I should rename it to `/regiveLegacies`.

**Comment by 1nsertTextHere** [comment]
yeah, and have /giveLegacy ______ only for creative or something

**Comment by lukawarren** [comment]
AFAIK it already should be
