### ISSUE TITLE
Glacen should freeze water-logged blocks

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#107]
I can freeze ice 12 block away, I feel like it should be 6 at the most.

**Comment by 1nsertTextHere** [comment]
Also, If there is like grass or seaweed (kelp) in the water, it doesnt freeze, which I feel like it should

**Comment by lukawarren** [comment]
Yeah, the range should be balanced, it was just an arbitrary number I chose. When Glacen gets levels soon, I'll do it then.
