### ISSUE TITLE
Stamina recovery rate wants changing

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#110]
1. I feel like it still regens too fast 2. Maybe make it like levels where it decreases by __ every level (aka, more stamina/less time to deplete) and the refill time stays the same forever, nothing changes (maybe we could add some sort of thing you can wear that increases stamina regen time later) 3. Make add a number value like the XP bar to show you what level stamina you are (maybe put it in a corner on our legacy UI)

**Comment by 1nsertTextHere** [comment]
|Maybe we could add an admin command where like you can change how many legacies have to be active for stamina to deplete. But I feel like it should be 1 active to deplete stamina, not 2

**Comment by lukawarren** [comment]
The issue of changing the config live should be solved when the guys at Forge [reimplement the mod config GUI](https://github.com/MinecraftForge/MinecraftForge/pull/7395)
