### ISSUE TITLE
Lumen Issues

### ISSUE THREAD

**Issue by Blue20Boy17** [lukawarren/Lorien-Legacies#13]
~~Lumen should make you resistant to lava as well, so that needs worked in~~

Also, you should be able to ignite yourself only if wearing armor, and the longer your ignited, your armor will lose durability (sort of like John's clothes in the books) and you'll be "naked" and not have any material on you to burn. it should be a manual thing, like launch a fireball at your feet and your ignited. Maybe being ignited can give you a power boost of sort? like maybe a little absorption or something?

Lights would be neat

these features would make Lumen the best Legacy xD

**Comment by lukawarren** [comment]
the player is currently immune to lava with lumen by the way

**Comment by Blue20Boy17** [comment]
Awesome
