### ISSUE TITLE
Legacy loading and world save

### ISSUE THREAD

**Issue by Blue20Boy17** [lukawarren/Lorien-Legacies#17]
When I create a new world, all Legacies I had in World 1 are also there in World 2, which shouldn't happen. Also, when Legacies are loaded after re-entering a world, they are all toggled, which also shouldn't happen.

**Comment by lukawarren** [comment]
I'll see if I can fix the toggling part now

**Comment by lukawarren** [comment]
Fixed the toggling part

**Comment by lukawarren** [comment]
Managed to replicate the other issue. Only seems to happen if legacies are blessed in both worlds.

**Comment by Blue20Boy17** [comment]
So if I give myself Lumen and Novis in World 1, and Accelix and Fortem in World 2, when I go back to World 1, I'll have Lumen, Novis, Accelix, an Fortem? Same for when I go back to World 2?

**Comment by lukawarren** [comment]
Forgot to test, but if World 2 is loaded after World 1 then World 2 will have both world's legacies since there are two instances of legacy manager

**Comment by lukawarren** [comment]
Anyway it's fixed now so yay
