### ISSUE TITLE
Accelex, Glacien issue

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#49]
When you run with Accelex and use Galcien, the game crashes
[crash-2020-04-05_10.21.50-server.txt](https://github.com/TheUltimateKerbonaut/Lorien-Legacies/files/4434087/crash-2020-04-05_10.21.50-server.txt)
[crash-2020-04-04_12.38.24-server.txt](https://github.com/TheUltimateKerbonaut/Lorien-Legacies/files/4434088/crash-2020-04-04_12.38.24-server.txt)

**Comment by lukawarren** [comment]
Fixed in the rewrite.
