### ISSUE TITLE
Avex speed adjustments

### ISSUE THREAD

**Issue by lukawarren** [lukawarren/Lorien-Legacies#5]
Whilst using the scrollbar works, it means the selected item of the player constantly changes. It's only a quality of life thing, but perhaps an alternative could be implemented? How about holding the shift key as well, and stopping the currently selected item changing?

**Comment by Blue20Boy17** [comment]
I agree, the hold shift thing is a great idea

**Comment by lukawarren** [comment]
It definitely needs a bell curve, otherwise the sensitivity is way too insane.
