### ISSUE TITLE
Avex issues

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#65]
So this one's got a lot. So, one, the stamina runs out way to quickly, it takes one second to be fully depleted. 2, it takes 1 second to refill, so even at level one you can fly forever. You dont glide, which I though was what we were doing. I thought we were making it like an elytra. Anyways, this makes it really hard to move. Also, I feel like you should take a little less fall damage because if you go up and back down twice, you die.

**Comment by lukawarren** [comment]
Fixed in the rewrite.
