### ISSUE TITLE
java.util.ConcurrentModificationException crash

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#66]
It just crashed, I dont know what else to say.
[crash-2020-04-11_12.51.04-server.txt](https://github.com/TheUltimateKerbonaut/Lorien-Legacies/files/4464987/crash-2020-04-11_12.51.04-server.txt)
 to say.

**Comment by lukawarren** [comment]
java.util.ConcurrentModificationException again ;)

I wonder if not doing computeLegacyTick() client-side would fix it since the client and server sides are on separate threads, hence the crash when they both computeLegacyTick() at the same time?

**Comment by lukawarren** [comment]
Well since the rewrite I haven't found this issue, so closing it.
