### ISSUE TITLE
Glacen bugs

### ISSUE THREAD

**Issue by Blue20Boy17** [lukawarren/Lorien-Legacies#68]
game crashes when trying to freeze water blocks under the surface layer
stamina doesn't drain when using (i know it'll be fixed when the level system is complete)

**Comment by lukawarren** [comment]
crash log?

**Comment by lukawarren** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/18/20 10:14 PM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:691)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:691)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Blue20Boy17'/408, l='New World', x=-69.20, y=63.00, z=489.01]]
	Chunk stats: ServerChunkCache: 1810 Drop: 0
	Level seed: -3883355915900563804
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (236,64,248), Chunk: (at 12,4,8 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13513 game time, 13513 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 65741 (now: false), thunder time: 66500 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 943750040 bytes (900 MB) / 2406481920 bytes (2295 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3584m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                                  | Signature |
	|:------ |:-------------- |:------------ |:--------------------------------------- |:--------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                           | None      |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                           | None      |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2847-universal.jar | None      |
	| LCHIJA | forge          | 14.23.5.2847 | forge-1.12.2-14.23.5.2847-universal.jar | None      |
	| LCHIJA | journeymap     | 1.12.2-5.7.0 | journeymap-1.12.2-5.7.0.jar             | None      |
	| LCHIJA | lorienlegacies | 1.0          | lorienlegacies-1.0.jar                  | None      |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Blue20Boy17'/408, l='New World', x=-69.20, y=63.00, z=489.01]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.19
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by lukawarren** [comment]
Fixed.
