### ISSUE TITLE
Legacy toggling

### ISSUE THREAD

**Issue by lukawarren** [lukawarren/Lorien-Legacies#7]
it doesn't work with Accelix, and possibly other legacies too

**Comment by lukawarren** [comment]
Not sure why I had this issue, but Accelix seems to work just fine at the moment. Just tested all the other key bindings, and they work flawlessly! Weird, huh? Marking this issue as closed since I can't reproduce it.

**Comment by lukawarren** [comment]
Actually, I _can_ reproduce this issue. Acquire legacies, then /kill yourself. After that toggling won't work.

**Comment by lukawarren** [comment]
Might be an issues with UUIDs changing upon death, who knows?

**Comment by Blue20Boy17** [comment]
I noticed this as well

**Comment by lukawarren** [comment]
Lol accidentally made a new issue for this yesterday. Well I've just done a temporary fix before multiplayer is added so I'm closing it for now.
