### ISSUE TITLE
Legacy blesser blessing twice

### ISSUE THREAD

**Issue by lukawarren** [lukawarren/Lorien-Legacies#8]

**Comment by Blue20Boy17** [comment]
Yesterday when I tried to give myself Lumen, it gave it to me eight times xD

**Comment by 1nsertTextHere** [comment]
oof, so how would one go about fixing that?

**Comment by Blue20Boy17** [comment]
idk xD...ask Kerbo xD

**Comment by lukawarren** [comment]
Hmm, well blessers are currently just items, and it seems you can use the item really really fast. If you figure out how to add some sort of a cooldown, that might work. Or, better yet, what about making the blessers food items (but obviously don't feed the player). That way they'd take a little bit of time to "eat",  and you could bless them in the function "onEaten". You can read about how to make custom food [here](https://suppergerrie2.com/minecraft-1-12-modding-with-forge-8-custom-food/).
