### ISSUE TITLE
Avex WASD controls

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#84]
Currently with avex you can only move forward, you can even stop. I feel like it should be like you are in creative mode. Maybe make it so that you are in the fly part of creative when you have avex activated and have stamina.

**Comment by lukawarren** [comment]
That's what Avex used to be like before we changed it. It was requested it was changed to be more like superman flying rather than Steve. It felt more "unique" that way I guess. 

We'll see what people think before we release the mod.

**Comment by 1nsertTextHere** [comment]
but superman can stop and start

**Comment by lukawarren** [comment]
Fair enough. Links in with another issue on Discord too. I'll add W and S controls.
