### ISSUE TITLE
Stamina bar issue

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#86]
Sometime that bar runs out before your stamina runs out. And it gets more and more noticeable as you level up and get more stamina.

**Comment by lukawarren** [comment]
Is this on singleplayer or multiplayer?

**Comment by 1nsertTextHere** [comment]
singleplayer

**Comment by lukawarren** [comment]
Not sure but this could still be present after the rewrite. Feel free to reopen the issue if it is.
