### ISSUE TITLE
Lumen level 1 does not have any active effects

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#87]
If Lumen is supposed to grant fire protection on its level 1 or something, it doesn't.

**Comment by lukawarren** [comment]
Fire damage is level 2, lava and dragon damage is level 4.

**Comment by 1nsertTextHere** [comment]
what are you supposed to do then you get Lumen xp?

**Comment by lukawarren** [comment]
When you gain XP you level up. @PhantomTheDev did the lumen stuff, but looking at the code I'm not sure if level 1 actually does anything? Not sure, try testing it.

**Comment by 1nsertTextHere** [comment]
thats what I was saying, level 1 doesnt do anything, therefore, you cant level up

**Comment by lukawarren** [comment]
Now it does :)
