### ISSUE TITLE
Pondus issue?

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#90]
Stamina is drained when pondus is active, not when you are walking on water. Its not really an issue, just, yeah.

**Comment by lukawarren** [comment]
Again, stamina hasn't been done for Pondus, it was just a copy-paste from the other generic legacies that didn't have keybinds or stuff. Adding it to the main stamina/levels issue.

**Comment by 1nsertTextHere** [comment]
ok, I was just testing and thats a thing I found. Also you never mentioned this ever, so I just put it here because I felt like it should be in the mod.

**Comment by lukawarren** [comment]
I think we misunderstood each other. Pondus levels and stamina *is* being added, just not yet.
