### ISSUE TITLE
Mod issue

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#99]
![image](https://user-images.githubusercontent.com/50081629/103100712-e3fe8b00-45e1-11eb-92df-5705ccfb3711.png)

heres the full log, 
[crash-2020-12-24_12.14.43-server.txt](https://github.com/TheUltimateKerbonaut/Lorien-Legacies/files/5740227/crash-2020-12-24_12.14.43-server.txt)

**Comment by 1nsertTextHere** [comment]
![image](https://user-images.githubusercontent.com/50081629/103100766-38a20600-45e2-11eb-8e5d-3b1be63b9338.png)
This happened right as I booted up the mod again 

Log: 
[crash-2020-12-24_12.18.39-server.txt](https://github.com/TheUltimateKerbonaut/Lorien-Legacies/files/5740230/crash-2020-12-24_12.18.39-server.txt)

**Comment by 1nsertTextHere** [comment]
this also may be a duplicate of issue #66

**Comment by lukawarren** [comment]
Yes, it is.
